# Bulk RNA-seq Analysis Environment
# Generated: 2025-11-06 12:14:51
# Environment: rnaseq_analysis
# Platform: Linux x86_64
#
name: rnaseq_analysis
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.44=h9d8b0ac_4
  - boost-cpp=1.85.0=h3c6214e_4
  - brotli-python=1.2.0=py312h67db365_0
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - cpython=3.12.12=py312hd8ed1ab_1
  - curl=8.17.0=h4e3cde8_0
  - cutadapt=5.2=py312h0fa9677_0
  - dnaio=1.2.2=py312hf67a6ed_0
  - expat=2.7.1=hecca717_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gfortran_impl_linux-64=15.2.0=h1b0a18f_7
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.14.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kaleido-core=0.2.1=h3644ca4_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libcblas=3.9.0=38_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.86.1=h32235b2_1
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjemalloc=5.3.0=h5888daf_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=15.2.0=hb13aed2_7
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - markdown=3.10=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - mathjax=2.7.7=ha770c72_3
  - mdurl=0.1.2=pyhd8ed1ab_1
  - multiqc=1.32=pyhdfd78af_1
  - narwhals=2.10.2=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nspr=4.38=h29cc59b_0
  - nss=3.117=h445c969_0
  - numpy=2.3.4=py312h33ff503_0
  - openjdk=25.0.1=h5755bd7_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=hadf4263_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.46=h1321c63_0
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.8=hadc24fc_1
  - pillow=12.0.0=py312h0889fd4_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.4.0=pyhd8ed1ab_0
  - polars=1.35.1=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.35.1=py310hffdcd12_0
  - polars-runtime-compat=1.35.1=py310hbcd5346_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py312h868fb18_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_1_cpython
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-isal=1.8.0=py312h4c3975b_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-zlib-ng=1.0.0=py312hd86e735_0
  - python_abi=3.12=8_cp312
  - pyyaml=6.0.3=py312h8a5da7c_0
  - r-base=4.5.2=hc038350_1
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py312h4c3975b_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.4=pyhd8ed1ab_0
  - rpds-py=0.28.0=py312h868fb18_1
  - salmon=1.10.3=haf24da9_3
  - samtools=1.22.1=h96c455f_0
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.51.0=heff268d_0
  - sysroot_linux-64=2.34=h087de78_2
  - tbb=2022.3.0=h8d10470_0
  - tiktoken=0.12.0=py312hd04cf1f_1
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xopen=2.0.2=pyh707e725_2
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2

prefix: "/home/davidec/micromamba/envs/rnaseq_analysis"
