name: rnaseq_analysis
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  # === R CORE ===
  - r-base=4.3.*
  
  # === R PACKAGES ===
  - r-tidyverse 
  - r-devtools
  
  # === BIOCONDUCTOR ===
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-reactomepa
  - bioconductor-enrichplot

  # === TOOLS ===
  - salmon
  - fastqc
  - multiqc
  - samtools
